export const dataDistrict = [
  { id: 1, district: 'Quận 1' },
  { id: 2, district: 'Quận 2' },
  { id: 3, district: 'Quận 3' },
  { id: 4, district: 'Quận 4' },
  { id: 5, district: 'Quận 5' },
  { id: 6, district: 'Quận 6' },
  { id: 7, district: 'Quận 7' },
  { id: 8, district: 'Quận 8' },
  { id: 9, district: 'Quận 9' },
  { id: 10, district: 'Quận 10' },
  { id: 11, district: 'Quận 11' },
  { id: 12, district: 'Quận 12' },
  { id: 13, district: 'Bình Thạnh' },
  { id: 14, district: 'Phú Nhuận' },
  { id: 15, district: 'Gò Vấp' },
  { id: 16, district: 'Bình Tân' },
  { id: 17, district: 'Tân Phú' },
  { id: 18, district: 'Thủ Đức' },
  { id: 19, district: 'Củ Chi' },
  { id: 20, district: 'Hóc Môn' },
  { id: 21, district: 'Bình Chánh' },
  { id: 22, district: 'Nhà Bè' },
  { id: 23, district: 'Cần Giờ' },
  { id: 24, district: 'Thành phố Thủ Đức' },
];
